- name: Setup Security
  become: yes
  hosts: all
  tasks:
    - name: Allow K3s ports on trusted zone
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        zone: trusted
        state: enabled
      loop: "{{ k3s_ports.split(',') }}"

    - name: Allow K3s sources on trusted zone
      ansible.posix.firewalld:
        source: "{{ item }}"
        permanent: true
        zone: trusted
        state: enabled
      loop: "{{ k3s_sources.split(',') }}"

    - name: Allow Tailscale ports on trusted zone
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        zone: trusted
        state: enabled
      loop: "{{ tailscale_ports.split(',') }}"

    - name: Allow Tailscale interface on trusted zone
      ansible.posix.firewalld:
        interface: "{{ tailscale_interface }}"
        permanent: true
        zone: trusted
        state: enabled

    - name: Enable IPv4 Masquerading on trusted zone
      ansible.posix.firewalld:
        permanent: true
        masquerade: true
        zone: trusted
        state: enabled

    - name: Enable IPv6 Masquerading on trusted zone
      ansible.posix.firewalld:
        permanent: true
        rich_rule: rule family=ipv6 masquerade
        zone: trusted
        state: enabled

    - name: Enable Masquerading on public zone
      ansible.posix.firewalld:
        permanent: true
        masquerade: true
        zone: public
        state: enabled

    - name: Enable IPv6 Masquerading on public zone
      ansible.posix.firewalld:
        permanent: true
        rich_rule: rule family=ipv6 masquerade
        zone: public
        state: enabled

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
