apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: netperf-client
  namespace: testing
  labels:
    app.kubernetes.io/name: netperf-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: netperf-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: netperf-client
    spec:
      containers:
        - name: netperf-client
          image: beenum/netperf:latest
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - "3600"
#          args:
#            - "-H"
#            - "netperf-server"
#            - "-l"
#            - "100"
#            - "-t"
#            - "TCP_RR"
#            - "--"
#            - "-o"
#            - "min_latency,mean_latency,max_latency"