apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "{{ .Values.name }}"
spec:
  acme:
    email: "{{ .Values.email }}"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: "{{ .Values.name }}-account-key"
    solvers:
      - dns01:
          cloudflare:
            email: "{{ .Values.email }}"
            apiTokenSecretRef:
              name: "{{ .Values.cloudflare_secret_name }}"
              key: "{{ .Values.cloudflare_secret_key }}"
