apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    # {{ PATCH_TIMESTAMP }}
    service:
      annotations:
        metallb.universe.tf/address-pool: {{ METALLB_POOL_NAME }}
      ipFamilyPolicy: RequireDualStack
      ipFamilies:
        - IPv6
        - IPv4
    ports:
      traefik:
        port: 9000
        expose: true
        exposedPort: {{ TRAEFIK_DASHBOARD_PORT }}
        protocol: TCP