apiVersion: v1
entries:
  velero-backup-restore:
  - apiVersion: v2
    appVersion: "1.0"
    created: "2025-09-11T23:33:37.105482+02:00"
    description: Automated backup and restore for Kubernetes resources using Velero
    digest: 3e353b9be5ac1eda9b18f9fa1c57452a5dcea2b674adcd63e9936cf89d627318
    keywords:
    - backup
    - restore
    - velero
    - kubernetes
    - scheduling
    - automation
    - disaster-recovery
    - pvc
    - volume-snapshots
    maintainers:
    - name: infra-lab
    name: velero-backup-restore
    urls:
    - https://beenum22.github.io/infra-lab/charts/velero-backup-restore-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-11T23:33:37.104902+02:00"
