apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metallb-speaker
  namespace: metallb-system
spec:
  template:
    spec:
      containers:
        - name: speaker
          image: quay.io/metallb/speaker:v0.13.7
          env:
            - name: METALLB_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP