apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: "{{ .Values.name }}"
spec:
  hostname: "{{ .Values.hostname }}"
  subnetRouter:
    advertiseRoutes:
      {{- range .Values.advertised_routes }}
      - {{ . | quote }}
      {{- end }}
