{{- range .Values.schedules }}
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "velero-schedule.labels" $ | nindent 4 }}
    schedule-name: {{ .name }}
spec:
  schedule: {{ .schedule | default $.Values.global.defaultSchedule | quote }}
  template:
    ttl: {{ .template.ttl | default $.Values.global.defaultTtl | quote }}
    {{- if .template.includedNamespaces }}
    includedNamespaces:
      {{- toYaml .template.includedNamespaces | nindent 6 }}
    {{- end }}
    {{- if .template.excludedNamespaces }}
    excludedNamespaces:
      {{- toYaml .template.excludedNamespaces | nindent 6 }}
    {{- end }}
    {{- if .template.includedResources }}
    includedResources:
      {{- toYaml .template.includedResources | nindent 6 }}
    {{- end }}
    {{- if .template.excludedResources }}
    excludedResources:
      {{- toYaml .template.excludedResources | nindent 6 }}
    {{- end }}
    {{- if .template.labelSelector }}
    labelSelector:
      {{- toYaml .template.labelSelector | nindent 6 }}
    {{- end }}
    snapshotVolumes: {{ .template.snapshotVolumes | default true }}
    storageLocation: {{ .template.storageLocation | default $.Values.global.storageLocation | quote }}
    {{- if .template.volumeSnapshotLocations }}
    volumeSnapshotLocations:
      {{- toYaml .template.volumeSnapshotLocations | nindent 6 }}
    {{- else }}
    volumeSnapshotLocations:
      {{- toYaml $.Values.global.volumeSnapshotLocations | nindent 6 }}
    {{- end }}
    {{- if .template.hooks }}
    hooks:
      {{- toYaml .template.hooks | nindent 6 }}
    {{- end }}
{{- end }}